"""Add video upload fields to media_assets

Revision ID: afdd2b7225c8
Revises: add_draft_version_to_courses
Create Date: 2026-05-12 07:36:29.419697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdd2b7225c8'
down_revision: Union[str, Sequence[str], None] = 'add_draft_version_to_courses'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the media_assets columns (SQLite doesn't support ALTER for foreign keys)
    op.add_column('media_assets', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('poster_url', sa.String(length=500), nullable=True))
    op.add_column('media_assets', sa.Column('streaming_url', sa.String(length=500), nullable=True))
    op.add_column('media_assets', sa.Column('upload_status', sa.String(length=30), nullable=False, server_default='ready'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'upload_status')
    op.drop_column('media_assets', 'streaming_url')
    op.drop_column('media_assets', 'poster_url')
    op.drop_column('media_assets', 'height')
    op.drop_column('media_assets', 'width')
    # ### end Alembic commands ###
